baseURL = "https://wooooov.github.io/"
languageCode = "en-us"
title = "Hugo-HT"
theme = "hugo-ht"
footnotereturnlinkcontents = "◀"
enableRobotsTXT = true
# enableGitInfo = true

[permalinks]
cn = "/cn/:year/:month/:day/:slug/"
en = "/en/:year/:month/:day/:slug/"
posts = "/posts/:year/:month/:day/:slug/"

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2
[[menu.en]]
    name = "Posts"
    url = "/en/posts/"
    weight = 3
[[menu.en]]
    name = "中文"
    url = "/cn/posts/"
    weight = 4
[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 1
[[menu.cn]]
    name = "日志"
    url = "/cn/posts/"
    weight = 2
[[menu.cn]]
    name = "English"
    url = "/"
    weight = 3

[params]
    description = "Peronal website of Your Name"
    homeText = "You just need a Hugo blog from scratch"
    # Please make sure `blogDirNmae` matches the name used in `menu` above:
    blogDirName = "posts"
    # singleLang = true
    defaultLang = "en"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs" 
    MathJaxVersion = "2.7.5"
    favicon = "media/dog-logo.jpg"
    # Edit by yourself:
    GithubEdit = "https://github.com/Wooooov/Wooooov.github.io/edit/master/content/"
    copyright = "&copy;"
    copyrightYear = "2020-2021"
    # Edit by yourself:
    GithubRepo = "https://github.com/Wooooov/Wooooov.github.io"
    # Edit by yourself:
    ContentSource = "https://raw.githubusercontent.com/Wooooov/Wooooov.github.io/master/content/" 

[params.logo]
  # Change the logo picture as your prefer:
  url = "media/dog-logo.jpg" # you can change it
  width = 50.0
  height = 50.0
  alt = "余忻萌：Sandy Yu"

[params.lang]

    [params.lang.author]
      en = "Your Name"
      cn = "你的名字"

    [params.lang.madeWith]
      en = "Made with"
      cn = "本站驱动"

    [params.lang.edit]
      en = "Suggest an edit of this page"
      cn = "编辑本页"

    [params.lang.lastupdate]
      en = "Last modified on"
      cn = "最后一次修改于"

    [params.lang.Sitelastupdate]
      en = "Site last updated on"
      cn = "最近一次更新于"

    [params.lang.sourceCode]
      en = "Content in"
      cn = "内容存于"

    [params.lang.subscribe]
      en = "Subscribe"
      cn = "订阅"

    [params.lang.license]
      en = "License"
      cn = "版权"

[params.busuanzi]
  enable = true
  # 是否开启全站独立访客数
  site_uv = true
  # 全站独立访客数前的图标或提示语
  site_uv_pre = '<i class="fa fa-user"></i>' 
  # 全站独立访客数后的图标或提示语
  site_uv_post = ''
  # 是否开启全站浏览量
  site_pv = true
  # 全站浏览量前的图标或提示语
  site_pv_pre = '<i class="fa fa-eye"></i>'
  # 全站浏览量后的图标或提示语
  site_pv_post = ''
  # 是否开启单页浏览量
  page_pv = true
  # 单页浏览量前的图标或提示语
  page_pv_pre = '<i class="far fa-eye fa-fw"></i>'
  # 单页浏览量后的图标或提示语
  page_pv_post = ''

[markup]
 defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false
  
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2

[imaging]
quality = 100